spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "spyder.gsc2024@gmail.com"
    password: "vuwucsyblvcarhfe"
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com
  datasource:
    username: root
    password: 1401
    url: jdbc:mysql://localhost:3306/movies
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
project:
  poster: poster/
base:
  url: "http://localhost:8080"
